"""Add stable role codes and update role metadata."""

# Generated by Django 5.1.15 on 2026-05-26 09:45

import re

from django.db import migrations, models


def populate_role_codes(apps, schema_editor):
    """Backfill role codes for existing role rows."""
    role_model = apps.get_model("roles", "Role")
    used_codes = set()

    for role in role_model.objects.order_by("id"):
        base_code = re.sub(r"[^a-z0-9]+", "-", role.name.lower()).strip("-")
        code = base_code or f"role-{role.pk}"

        if code in used_codes:
            code = f"{code}-{role.pk}"

        role.code = code
        role.save(update_fields=["code"])
        used_codes.add(code)


class Migration(migrations.Migration):

    dependencies = [
        ("roles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="code",
            field=models.CharField(
                choices=[("admin", "Admin"), ("member", "Member")],
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.RunPython(populate_role_codes, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name="role",
            options={"ordering": ["code"]},
        ),
        migrations.AlterField(
            model_name="role",
            name="code",
            field=models.CharField(
                choices=[("admin", "Admin"), ("member", "Member")],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
