"""Tests for user dashboard metrics and rendering."""

import pytest
from django.urls import reverse

from apps.dashboard.services import get_user_dashboard_context
from apps.jobs.factories import ApplicationNoteFactory, JobApplicationFactory
from apps.jobs.models import JobApplication
from apps.users.factories import UserFactory


@pytest.mark.django_db
def test_dashboard_context_returns_empty_metrics_for_new_user() -> None:
    """A new user should receive zeroed dashboard metrics."""
    user = UserFactory()

    context = get_user_dashboard_context(user)

    assert context.metrics == {
        "total_applications": 0,
        "active_applications": 0,
        "saved_jobs": 0,
        "follow_ups": 0,
        "interviews": 0,
        "offers": 0,
        "rejections": 0,
        "notes": 0,
    }


@pytest.mark.django_db
def test_dashboard_context_counts_only_current_user_data() -> None:
    """Dashboard metrics should not include another user's records."""
    user = UserFactory()
    other_user = UserFactory()
    applied_application = JobApplicationFactory(
        owner=user,
        status=JobApplication.Status.APPLIED,
    )
    JobApplicationFactory(
        owner=user,
        status=JobApplication.Status.INTERVIEWING,
    )
    JobApplicationFactory(
        owner=user,
        status=JobApplication.Status.OFFER,
    )
    JobApplicationFactory(
        owner=other_user,
        status=JobApplication.Status.REJECTED,
    )
    ApplicationNoteFactory(application=applied_application)
    ApplicationNoteFactory(application=applied_application)

    context = get_user_dashboard_context(user)

    assert context.metrics["total_applications"] == 3
    assert context.metrics["active_applications"] == 2
    assert context.metrics["saved_jobs"] == 0
    assert context.metrics["follow_ups"] == 0
    assert context.metrics["interviews"] == 1
    assert context.metrics["offers"] == 1
    assert context.metrics["rejections"] == 0
    assert context.metrics["notes"] == 2


@pytest.mark.django_db
def test_user_dashboard_requires_authentication(client) -> None:
    """Anonymous users should be redirected from the dashboard."""
    response = client.get(reverse("dashboard:user"))

    assert response.status_code == 302


@pytest.mark.django_db
def test_user_dashboard_renders_actionable_empty_state(client) -> None:
    """New users should see a clear first-application action."""
    user = UserFactory()
    client.force_login(user)

    response = client.get(reverse("dashboard:user"))

    assert response.status_code == 200
    assert b"Add your first role" in response.content
    assert b"View applications" in response.content
    assert b"Add application" in response.content


@pytest.mark.django_db
def test_user_dashboard_renders_metrics(client) -> None:
    """The dashboard should render metrics generated by the service layer."""
    user = UserFactory()
    JobApplicationFactory(owner=user, status=JobApplication.Status.SAVED)
    JobApplicationFactory(owner=user, status=JobApplication.Status.APPLIED)
    JobApplicationFactory(owner=user, status=JobApplication.Status.SCREENING)
    JobApplicationFactory(owner=user, status=JobApplication.Status.INTERVIEWING)
    JobApplicationFactory(owner=user, status=JobApplication.Status.REJECTED)
    client.force_login(user)

    response = client.get(reverse("dashboard:user"))

    assert response.status_code == 200
    assert response.context["metrics"]["total_applications"] == 5
    assert response.context["metrics"]["active_applications"] == 3
    assert response.context["metrics"]["saved_jobs"] == 1
    assert response.context["metrics"]["follow_ups"] == 1
    assert response.context["metrics"]["interviews"] == 1
    assert response.context["metrics"]["rejections"] == 1
    assert b"Saved jobs" in response.content
    assert b"Follow-ups" in response.content
    assert b"Interviews" in response.content
    assert b"Total Applications" in response.content
    assert b"Active Applications" in response.content
    assert b"Offers" in response.content
    assert b"Rejections" in response.content
    assert b"Notes" in response.content


@pytest.mark.django_db
def test_user_dashboard_renders_status_grouped_pipeline_cards(client) -> None:
    """The dashboard should render user-owned cards in pipeline columns."""
    user = UserFactory()
    saved_application = JobApplicationFactory(
        owner=user,
        title="Saved Platform Engineer",
        status=JobApplication.Status.SAVED,
    )
    applied_application = JobApplicationFactory(
        owner=user,
        title="Applied Platform Engineer",
        status=JobApplication.Status.APPLIED,
    )
    interview_application = JobApplicationFactory(
        owner=user,
        title="Interview Platform Engineer",
        status=JobApplication.Status.INTERVIEWING,
    )
    client.force_login(user)

    response = client.get(reverse("dashboard:user"))

    assert response.status_code == 200
    assert list(response.context["saved_applications"]) == [saved_application]
    assert list(response.context["applied_applications"]) == [applied_application]
    assert list(response.context["interviewing_applications"]) == [
        interview_application
    ]
    assert saved_application.title.encode() in response.content
    assert applied_application.title.encode() in response.content
    assert interview_application.title.encode() in response.content
