"""Tests for user dashboard metrics and rendering."""

import pytest
from django.urls import reverse

from apps.dashboard.services import get_user_dashboard_context
from apps.jobs.factories import ApplicationNoteFactory, JobApplicationFactory
from apps.jobs.models import JobApplication
from apps.users.factories import UserFactory


@pytest.mark.django_db
def test_dashboard_context_returns_empty_metrics_for_new_user() -> None:
    """A new user should receive zeroed dashboard metrics."""
    user = UserFactory()

    context = get_user_dashboard_context(user)

    assert context.metrics == {
        "total_applications": 0,
        "active_applications": 0,
        "interviews": 0,
        "offers": 0,
        "rejections": 0,
        "notes": 0,
    }


@pytest.mark.django_db
def test_dashboard_context_counts_only_current_user_data() -> None:
    """Dashboard metrics should not include another user's records."""
    user = UserFactory()
    other_user = UserFactory()
    applied_application = JobApplicationFactory(
        owner=user,
        status=JobApplication.Status.APPLIED,
    )
    JobApplicationFactory(
        owner=user,
        status=JobApplication.Status.INTERVIEWING,
    )
    JobApplicationFactory(
        owner=user,
        status=JobApplication.Status.OFFER,
    )
    JobApplicationFactory(
        owner=other_user,
        status=JobApplication.Status.REJECTED,
    )
    ApplicationNoteFactory(application=applied_application)
    ApplicationNoteFactory(application=applied_application)

    context = get_user_dashboard_context(user)

    assert context.metrics["total_applications"] == 3
    assert context.metrics["active_applications"] == 2
    assert context.metrics["interviews"] == 1
    assert context.metrics["offers"] == 1
    assert context.metrics["rejections"] == 0
    assert context.metrics["notes"] == 2


@pytest.mark.django_db
def test_user_dashboard_requires_authentication(client) -> None:
    """Anonymous users should be redirected from the dashboard."""
    response = client.get(reverse("dashboard:user"))

    assert response.status_code == 302


@pytest.mark.django_db
def test_user_dashboard_adds_metrics_to_context(client) -> None:
    """The dashboard should expose metrics generated by the service layer."""
    user = UserFactory()
    JobApplicationFactory(owner=user, status=JobApplication.Status.APPLIED)
    JobApplicationFactory(owner=user, status=JobApplication.Status.REJECTED)
    client.force_login(user)

    response = client.get(reverse("dashboard:user"))

    assert response.status_code == 200
    assert response.context["metrics"]["total_applications"] == 2
    assert response.context["metrics"]["active_applications"] == 1
    assert response.context["metrics"]["rejections"] == 1


@pytest.mark.django_db
def test_user_dashboard_adds_recent_activity_to_context(client) -> None:
    """The dashboard should expose recent user-owned applications."""
    user = UserFactory()
    application = JobApplicationFactory(
        owner=user,
        title="Platform Engineer",
        company="Recent Ltd",
    )
    client.force_login(user)

    response = client.get(reverse("dashboard:user"))

    assert response.status_code == 200
    assert list(response.context["recent_applications"]) == [application]
